(dynamic_include ../jerry-build/libjerry.inc)

(library
  (name umbilicus)
  (public_name umbilicus)
  (synopsis "dune testing")
  (modules umbilicus)
  (foreign_stubs
    (language c)
    (names ocaml_umbilicus)
    (flags :standard
           -I../libjerry
           ; hack to ensure that libjerry.so is copied to this
           ; directory by the rule in libjerry.inc <sigh>
           -DDUNE_DEP=%{dep:libjerry.so}))
  (library_flags :standard
                 -ccopt "-L$CAMLORIGIN"
                 -ccopt "-Wl,-rpath,$CAMLORIGIN")
  (c_library_flags :standard
                   -ljerry -Lumbilicus/
                   -Wl,-rpath,../lib)
)

